nome=str(input('qual seu nome completo? '))
maiusculo=nome.upper()
print(f'seu nome todo em maisculo dica: {maiusculo}')
minusculo=nome.lower()
print(f'seu nome todo em minusculo fica: {minusculo}')
quantidade=len(nome)
print(f'seu nome tem {quantidade} de letras')
primeiro_nome=nome.split()
print(f'seu primeiro nome é {primeiro_nome[0]} e tem {len(primeiro_nome[0])} letras')